# Generated by Django 4.0.6 on 2022-07-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0004_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_string',
            field=models.CharField(default='unknown_user', max_length=100),
        ),
    ]
