# Generated by Django 4.0.6 on 2022-07-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0005_client_user_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_string',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
