# Generated by Django 4.0.6 on 2022-07-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0008_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=300),
        ),
    ]
