# Generated by Django 4.0.6 on 2022-07-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0009_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='client',
            name='end',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='start',
            field=models.CharField(default='', max_length=300),
        ),
    ]
