# Generated by Django 4.0.6 on 2022-07-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0010_rename_name_client_title_client_end_client_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='end',
        ),
        migrations.RemoveField(
            model_name='client',
            name='start',
        ),
    ]
