# Generated by Django 4.0.6 on 2022-07-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0011_rename_title_client_name_remove_client_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='client',
            name='end',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='start',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
